sudo: required

services:
  - docker

language: node_js
node_js:
  - "node"

env:
  global:
    - DOCKER_REGISTRY=registry.cn-beijing.aliyuncs.com
    - DOCKER_REPO=$DOCKER_REGISTRY/36node/sketch-react

after_success:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_TAG ; fi`
  - if ([ ! -z "$TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$SKIP_BUILD" != "true" ]); then
      echo "Starting build image with tag ${TAG}";
      NODE_ENV=production npm run build;
      docker login -u $DOCKER_USER -p $DOCKER_PASS $DOCKER_REGISTRY;
      docker build -t $DOCKER_REPO:$TAG .;
      docker push $DOCKER_REPO:$TAG;
    fi
